apiVersion: skaffold/v4beta3
kind: Congif
manifests:
  rawYaml:
  - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
  - image: sreekanthlakka/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: .
  - image: sreekanthlakka/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.js*'
        dest: .
  - image: sreekanthlakka/main
    context: main
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.js*'
        dest: .
  - image: sreekanthlakka/notification
    context: notification
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.js*'
        dest: .
  - image: sreekanthlakka/execution-engine
    context: executionEngine
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.js*'
        dest: .

