apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author-mongo
  template:
    metadata:
      labels:
        app: author-mongo
    spec:
      containers:
      - name: author-mongo
        image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: author-mongo-srv
spec:
  selector:
    app: author-mongo
  ports:
  - name: author-mongo-db
    protocol: TCP
    port: 27017
    targetPort: 27017
