apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-engine-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: execution-engine
  template:
    metadata:
      labels:
        app: execution-engine
    spec:
      serviceAccountName: sree-service-account
      containers:
      - name: execution-engine
        image: sreekanthlakka/execution-engine
        env:
        - name: NATS_URL
          value: 'http://nats-srv:4222'
        - name: NATS_CLUSTER_ID
          value: 'leetcode'
        - name: NATS_CLIENT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_SERVICE_HOST
          value: "kubernetes.default.svc"
        - name: KUBERNETES_SERVICE_PORT
          value: "443"
---
apiVersion: v1
kind: Service
metadata:
  name: execution-engine-srv
spec:
  selector:
    app: execution-engine
  ports:
  - name: execution-engine
    protocol: TCP
    port: 3000
    targetPort: 3000
