apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: leetcode.dev
    http:
      paths:
      - path: /api/v1/users/?(.*)
        pathType: Prefix
        backend:
          service:
            name: auth-srv
            port:
              number: 3000
      - path: /api/v1/problemSubmit/?(.*)
        pathType: Prefix
        backend:
          service:
            name: main-srv
            port:
              number: 3000
      - path: /api/v1/addProblems/?(.*)
        pathType: Prefix
        backend:
          service:
            name: author-srv
            port:
              number: 3000
      - path: /?(.*)
        pathType: Prefix
        backend:
          service:
            name: client-srv
            port:
              number: 5173
