# # rolebinding.yaml
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: read-pods
#   namespace: default
# subjects:
# - kind: ServiceAccount
#   name: sree-service-account
#   namespace: default
# roleRef:
#   kind: Role
#   name: pod-reader
#   apiGroup: rbac.authorization.k8s.io


apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: execution-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: sree-service-account
  namespace: default
roleRef:
  kind: Role
  name: execution-role
  apiGroup: rbac.authorization.k8s.io

