# pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: problems-data-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/temp

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: problems-data-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

