# pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: problems-data-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/shared
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: problems-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

