name: deploy-execution-engine
on:
    push:
        branches:
            - master
        paths:
            - "executionEngine/**"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd executionEngine && docker build -t sreekanthlakka/execution-engine .
            - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push sreekanthlakka/execution-engine
            - uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            - run: doctl kubernetes cluster kubeconfig save leetcode
            - run: kubectl rollout restart deployment execution-engine-depl
