name: test-main
on:
  pull_request:
    paths:
      -  "main/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses:  actions/checkout@v2
      -  run: cd main && npm install  && npm run test:ci
