name: test-author
on:
  pull_request:
    paths:
      -  "author/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses:  actions/checkout@v2
      -  run: cd author && npm install  && npm run test:ci
