name: test-likes
on:
    pull_request:
        paths:
            - "likes/**"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd likes && npm install && npm run test:ci
